### ISSUE TITLE
数据库db.sql 插入user的语句多出一个值

### ISSUE THREAD

**Issue by dongnanyanhai** [linhecheng/cmlphp-demo-background#1]
pr_users 表只有10个字段，

db.sql中最后插入pr_users的语句有11个值：

INSERT INTO `pr_users` VALUES ('1','1', 'admin', '超级管理员', '60b72813b1f4cd74ae1f5eaa4c5bb96c', '1476252909', '0', '1476244882', '1', '0', '');

另外建议默认缓存使用file，可能有部分用户在windows下的php环境没有安装Redis。

**Comment by linhecheng** [comment]
感谢提醒，已修改。
